spring:
    application:
        name: homeListener



    jackson:
        serialization:
            write-date-keys-as-timestamps: false

    profiles:
        include: credential

springdoc:
    show-login-endpoint: true

logging:
    level:
        com:
            project:
                homeListener: DEBUG